version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
  pre_build:
    commands:
      - echo "Installing dependencies and executing unit tests - `pwd`"
      - cd deployment
      - if [ -f ./run-unit-tests.sh ]; then chmod +x ./run-unit-tests.sh && ./run-unit-tests.sh; fi
      - echo "Installing dependencies and executing unit tests completed `date`"      
  build:
    commands:
      - echo "Starting build `date` in `pwd`"
      - chmod +x ./build-s3-dist.sh && ./build-s3-dist.sh $DIST_OUTPUT_BUCKET $SOLUTION_NAME $VERSION
  post_build:
    commands:
      - echo "Retrieving next stage buildspec `date` in `pwd`"
      - aws s3 cp s3://aws-solutions-build-assets/changelog-spec.yml ../buildspec.yml
      - echo "Retrieving next stage buildspec complete"
      - echo "Post build completed on `date`"

artifacts:
  files:
    - .git/**/*
    - deployment/**/*
    - buildspec.yml
    - CHANGELOG.md
    - .cfnnagignore
