name: GitHub Pages

on:
  push:
    branches:
      - chinese-support  # Set a branch name to trigger deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python3 -m pip install mkdocs            # install mkdocs 
          python3 -m pip install mkdocs-material   # install material theme
      
      - name: Build mkdocs
        run: |
          sed -i 's/zh-branded/zh/g' docs/mkdocs.zh.yml
          sed -i 's/en-branded/en/g' docs/mkdocs.en.yml
          mkdocs build -f ./docs/mkdocs.en.yml
          mkdocs build -f ./docs/mkdocs.zh.yml
          cp -av ./docs/index.html ./docs/site
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/chinese-support' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/site